# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: councils
email: adam@ewire.co.uk
description: > # this means to ignore newlines until "baseurl:"
  some people I have met—the ways that we work together
baseurl: "councils" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _adamburton
github_username:  adamburton

# Build settings
markdown: kramdown
